Algoritmo "lerNumeroReal"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Thiago Sombra
// Descrição   : Lê um número real e imprime.
// Autor(a)    : Erick E. Sousa Lima
// Data atual  : 30/03/2020
Var
   // Seção de Declarações das variáveis
   r : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um número real")
   leia(r)
   escreval(r)

Fimalgoritmo