Algoritmo "kgParaLibras"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Thiago Sombra
// Descrição   : Converte uma massa de Kg para Libras.
// Autor(a)    : Erick E. Sousa Lima
// Data atual  : 30/03/2020
Var
   // Seção de Declarações das variáveis
   K,L : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite a massa em Kg:")
   leia(K)
   L := K/0.45
   escreval("Esta massa em Libras é:", L)

Fimalgoritmo