Algoritmo "librasParaKg"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Thiago Sombra
// Descrição   : Converte uma massa de Libras para Kg.
// Autor(a)    : Erick E. Sousa Lima
// Data atual  : 30/03/2020
Var
   // Seção de Declarações das variáveis
   K,L : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite a massa em Libras:")
   leia(L)
   K := L*0.45
   escreval("Esta massa em Kg é:", K)

Fimalgoritmo